Vagrant.configure(2) do |config|

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end

    config.vm.define "master-node" do |master|
        master.vm.box = "hashicorp/bionic64"
        master.vm.network "private_network", ip: "192.168.50.2"
    end
    
    config.vm.define "worker-node1" do |worker1|
        worker1.vm.box = "hashicorp/bionic64"
        worker1.vm.network "private_network", ip: "192.168.50.3"
    end

    # config.vm.define "worker-node2" do |worker2|
    #     worker2.vm.box = "hashicorp/bionic64"
    #     worker2.vm.network "private_network", ip: "192.168.50.4"
    # end
end