---
- hosts: nodes
  become: yes

  tasks:

    - name: Chceck if nodes are up and running
      ping:

    - name: Update apt
      apt: 
        update_cache: yes

    - name: Install required packages to add docker repository
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker's repo
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      
    - name: Setup stable repository
      shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    
    - name: Update apt
      apt: 
        update_cache: yes
    
    - name: Install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    
    - name: Check if docker is up and running
      shell: docker ps